Name:    "Sufyan Afzal"
Reg No:  "FA23-BAI-061"
    Lab 3 Tasks

Q.1 : Import the numpy package under the name np

In [ ]:
import numpy as np

Q.2 : Create a null vector of size 10

In [2]:
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Q.3 : Create a null vector of size 10 but the fifth value which is 1

In [3]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q.4 : Create a vector with values ranging from 10 to 49

In [4]:
import numpy as np
a = np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Q.5 : Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
import numpy as np
a = np.full((3,3),None)
a = np.arange(0,8)
print(a)

[0 1 2 3 4 5 6 7]


Q.6 : Create a 10x10 array with random values and find the minimum and maximum values

In [6]:
import numpy as np
a = np.random.random((10,10))
print("Araay : ",a)
print("Max value : ",np.max(a))
print("Min value :",np.min(a))

Araay :  [[0.6457422  0.03824639 0.63386685 0.0915384  0.40204297 0.30938811
  0.68712806 0.00534683 0.36171019 0.06330089]
 [0.13567139 0.59890618 0.65844456 0.84816862 0.10972924 0.72681501
  0.01315818 0.57796597 0.26802747 0.03401042]
 [0.90962477 0.48080986 0.59859371 0.3280861  0.66614481 0.38055847
  0.91842318 0.67548153 0.97912608 0.15721387]
 [0.83899944 0.36978901 0.15483451 0.18270821 0.13968036 0.71943116
  0.89820166 0.24821636 0.95413927 0.34370058]
 [0.47714921 0.9561346  0.43392111 0.92208496 0.39695146 0.13412183
  0.80232466 0.74237247 0.46642131 0.7079835 ]
 [0.63043325 0.49261946 0.95620474 0.86746718 0.8890576  0.07813389
  0.33577331 0.31098294 0.86604652 0.56647426]
 [0.25055633 0.40803878 0.85395468 0.60120256 0.29324016 0.87268078
  0.38039122 0.21443782 0.64857184 0.95871783]
 [0.87933605 0.78237135 0.29954261 0.83961502 0.23024861 0.51165727
  0.80431942 0.97809463 0.43097339 0.05093409]
 [0.88041233 0.16179459 0.07028926 0.85814224 0.89619837 0.11103945
  0

Q.7 : Create a 5x5 matrix with row values ranging from 0 to 4

In [7]:
import numpy as np
a = np.tile(np.arange(5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Q.8 : Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [8]:
import numpy as np
a = np.linspace(0.1,0.9,10)
print(a)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


Q.9 : Create a 2d array with 1 on the border and 0 inside

In [9]:
import numpy as np
m , n = 5 , 5
a = np.ones((m,n))
a[1:-1 , 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q.10 : Create a random vector of size 10 and sort it

In [10]:
import numpy as np
a = np.random.random(10)
print("Before sorting : ",a)
print()
print("After Sorting : ",np.sort(a))

Before sorting :  [0.70380173 0.33389788 0.154884   0.06757122 0.3683259  0.90095832
 0.5211829  0.29579177 0.85450516 0.70555021]

After Sorting :  [0.06757122 0.154884   0.29579177 0.33389788 0.3683259  0.5211829
 0.70380173 0.70555021 0.85450516 0.90095832]


Q.11 : Subtract the mean of each row of an array

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
wholeMean = np.mean(a)
print("Mean of a matrix : ",wholeMean)
coloumnMean = np.mean(a, axis=0, keepdims=True)
print("\nThe coloumn mean : ",coloumnMean)
rowMean = np.mean(a,axis =1, keepdims=True)
print("The Row mean : \n",rowMean)
resultMatrix = np.subtract(a,rowMean)
print("\nThe result matrix after subtraction : \n",resultMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of a matrix :  5.0

The coloumn mean :  [[4. 5. 6.]]
The Row mean : 
 [[2.]
 [5.]
 [8.]]

The result matrix after subtraction : 
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


Q.12 : create a 2D array, swap two rows of an array

In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Before swapping : \n",a)
a[[0,2]] = a[[2,0]]
print("\nAfter swapping : \n",a)

Before swapping : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After swapping : 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Q.13 : Find the number of occurrences of a sequence in an array

In [4]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[1,2,3]])
sequence = [1,2,3]
occurencesRow = np.sum((a==sequence).all(axis=1))
print("Number of Occurences in a sequense(Row) : ",occurencesRow)
occurencesColoumn = np.sum((a==sequence).all(axis=0))
print("Number of Occurences in a sequense(Coloumn) : ",occurencesColoumn)

Number of Occurences in a sequense(Row) :  2
Number of Occurences in a sequense(Coloumn) :  0


Q.14 : Combining a one and a two-dimensional Array

In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix a : \n",a)
b = np.array([[3,2,1]])
print("\nMatrix B : \n",b)
print("\nVertical Stack : \n",np.vstack((a,b)))
b = b.reshape(-1,1)
print("\nHorizontal Stack : \n",np.hstack((a,b)))

Matrix a : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B : 
 [[3 2 1]]

Vertical Stack : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 1]]

Horizontal Stack : 
 [[1 2 3 3]
 [4 5 6 2]
 [7 8 9 1]]


Q.15 :  Flatten a 2d array into 1d array

In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix a : \n",a)
print("\nFlatting an array using flatten() : \n",a.flatten())
print("\nFlatting an array using ravel() : \n",a.ravel())

Matrix a : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flatting an array using flatten() : 
 [1 2 3 4 5 6 7 8 9]

Flatting an array using ravel() : 
 [1 2 3 4 5 6 7 8 9]


Q.16 : How can one determine the occurrence frequency of distinct values within an array

In [7]:
import numpy as np
a = np.array([[1,2,3],[3,2,1],[4,1,3]])
b = np.array([[1,2,3,3,4,5,5,5,6,7,7,7,7,7,7]])
aUnique, aCounts = np.unique(a, return_counts = True)
print("Unique occurences in \"a\" : ",aUnique)
print("Number of unique counts vlaues in \"a\" : ",aCounts)
bUnique, bCounts = np.unique(b, return_counts= True)
print("\nUnique occurences in \"b\" : ",bUnique)
print("Number of unique counts vlaues in \"b\" : ",bCounts)

Unique occurences in "a" :  [1 2 3 4]
Number of unique counts vlaues in "a" :  [3 2 3 1]

Unique occurences in "b" :  [1 2 3 4 5 6 7]
Number of unique counts vlaues in "b" :  [1 1 2 1 3 1 6]


Q.17 : Compute the determinant of a matrix

In [9]:
import numpy as np
a = np.array([[1,2,3],[3,2,1],[4,1,3]])
print("Determinant of Matrix : ",np.linalg.det(a))

Determinant of Matrix :  -19.999999999999996


Q.18 : Ways to add row/columns in an array

In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a)
print("\nSum along coloumns : ",np.sum(a,axis=0))
print()
print()
print(b)
print("\nSum along rows : ",np.sum(b,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum along coloumns :  [12 15 18]


[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum along rows :  [24 15  6]


Q.19 : Convert a matrix into a list

In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix : \n",a)
print("\n Array to List : ",a.tolist())
print("\n Array to List (Flatten): ",a.flatten().tolist())

Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Array to List :  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

 Array to List (Flatten):  [1, 2, 3, 4, 5, 6, 7, 8, 9]


Q.20 : Calculate inner, outer, and cross products of matrices and vectors

In [12]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("\n 2 Dimentinal: \n")
print("Dot Product(2D): \n", a.dot(b))
print("\nInner Product(2D): \n",np.inner(a,b))
print("\nOuter Product(2D): \n",np.outer(a,b))
print("\nCross Product(2D): \n",np.cross(a,b))
c = np.array([1,2,3])
d = np.array([3,2,1])
print("\n\n")
print("-"*40)
print("#"*40)
print("-"*40)
print("\n\n\n 1 Dimentinal: \n")
print("\nDot Product(1D): \n", np.dot(c,d))
print("\nInner Product(1D): \n",np.inner(c,d))
print("\nOuter Product(1D): \n",np.outer(c,d))
print("\nCross Product(1D): \n",np.cross(c,d))


 2 Dimentinal: 

Dot Product(2D): 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Inner Product(2D): 
 [[ 46  28  10]
 [118  73  28]
 [190 118  46]]

Outer Product(2D): 
 [[ 9  8  7  6  5  4  3  2  1]
 [18 16 14 12 10  8  6  4  2]
 [27 24 21 18 15 12  9  6  3]
 [36 32 28 24 20 16 12  8  4]
 [45 40 35 30 25 20 15 10  5]
 [54 48 42 36 30 24 18 12  6]
 [63 56 49 42 35 28 21 14  7]
 [72 64 56 48 40 32 24 16  8]
 [81 72 63 54 45 36 27 18  9]]

Cross Product(2D): 
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]



----------------------------------------
########################################
----------------------------------------



 1 Dimentinal: 


Dot Product(1D): 
 10

Inner Product(1D): 
 10

Outer Product(1D): 
 [[3 2 1]
 [6 4 2]
 [9 6 3]]

Cross Product(1D): 
 [-4  8 -4]
